# Advance indexing 

###    1.normal indexing and slicing

In [22]:
a= np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
## get me a 6
a[1,2]

6

In [ ]:
## get me 5,6,7,9,10,11
a[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

### 2.Fancing indexing

In [ ]:
## rows 2,3,5
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [28]:
## col 0,2,3
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

### Boolean indexing

In [29]:
a= np.random.randint(1,100,24).reshape(6,4)
a

array([[56, 63, 90,  5],
       [69, 37, 89, 61],
       [94,  4, 10, 59],
       [79, 39, 86,  1],
       [10, 75, 61, 66],
       [55, 77, 42, 67]])

In [30]:
## find all the numbers greater than 50
a[a>50]

array([56, 63, 90, 69, 89, 61, 94, 59, 79, 86, 75, 61, 66, 55, 77, 67])

In [31]:
## find out even numbers
a[a%2==0]

array([56, 90, 94,  4, 10, 86, 10, 66, 42])

In [32]:
## find all the numbers greater than 50 and even
a[(a>50)& (a%2==0)] ## we use & for boolean opreations 

array([56, 90, 94, 86, 66])