# Broadcasting

### The term broadcasting describe how Numpy treats arrays with different shapes during arithmetic operations.
### The smaller array is "broadcast" across the larger array so that they have compatible shapes.

In [1]:
## same shape 
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
print (a)
print(b)

print(a+b)  # element-wise addition

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [2]:
## diff shape
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (2,3) for addition

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


## Broadcasting Rules
### 1.make the two arrays have the same number of dimensions.
####    i. If the sizes of each dimension of the two arrays do not match ,dimensions with size 1 are stretched to the size of the other array.
### 2. make each dimension of the two arrays the same size.
####   i. If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
####   ii.if there is a dimension with size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [6]:
## examples 
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
 
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [8]:
 
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition


[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
 
a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition


[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [11]:
 
a=np.array([1])
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition


[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [12]:
 
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)  # broadcasting: b is broadcasted to shape (4,3) for addition


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 