In [1]:
import numpy as np
a=np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [2]:
np.isnan(a)

array([False, False, False, False,  True, False])

In [3]:
a[np.isnan(a)]

array([nan])

In [4]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])