## np.sort

#### return a sorted copy of an array

```python

In [1]:
## code
import numpy as np
a=np.random.randint(1,100,15)
a

array([ 4, 92, 29, 28, 15, 61, 42, 22, 89, 92, 67, 15, 79, 97, 13])

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[88, 82,  9, 47],
       [30, 81, 49, 27],
       [52, 21,  8, 87],
       [11, 79, 31, 68],
       [98, 64, 49, 17],
       [81,  4, 54, 55]])

In [ ]:
np.sort(a) ## sort the array a in ascending order

array([ 4, 13, 15, 15, 22, 28, 29, 42, 61, 67, 79, 89, 92, 92, 97])

In [6]:
## descending order
np.sort(a)[::-1] ## sort the array a in descending order

array([97, 92, 92, 89, 79, 67, 61, 42, 29, 28, 22, 15, 15, 13,  4])

In [ ]:
np.sort(b)## row wise sort

array([[ 9, 47, 82, 88],
       [27, 30, 49, 81],
       [ 8, 21, 52, 87],
       [11, 31, 68, 79],
       [17, 49, 64, 98],
       [ 4, 54, 55, 81]])

In [5]:
## column wise sort
np.sort(b, axis=0)  ## column wise sort

array([[11,  4,  8, 17],
       [30, 21,  9, 27],
       [52, 64, 31, 47],
       [81, 79, 49, 55],
       [88, 81, 49, 68],
       [98, 82, 54, 87]])