In [1]:
## np.histogram tells us how many values fall into each bin
import numpy as np

In [2]:
a=np.random.randint(1,100,15)
a

array([68, 22, 37, 12, 89, 72, 19, 75, 74, 44, 90, 38, 46, 85, 81])

In [3]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 1, 2, 2, 0, 1, 3, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))