In [1]:
## np.isin with the help of this funtion we can check whether elements of one array are present in another array.
import numpy as np
a=np.random.randint(1,100,15)
a

array([19, 64, 99,  9, 63, 16, 61, 61, 74, 22, 97, 44, 99, 71,  1])

In [6]:
items=[10,20,30,40,50,61,70,80,90,99]

In [7]:
a[np.isin(a,items)]

array([99, 61, 61, 99])

In [10]:
## np.flip is a function that reverses the order of elements in an array along a specified axis.
a

array([19, 64, 99,  9, 63, 16, 61, 61, 74, 22, 97, 44, 99, 71,  1])

In [9]:
np.flip(a)

array([ 1, 71, 99, 44, 97, 22, 74, 61, 61, 16, 63,  9, 99, 64, 19])

In [11]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[50,  7, 62, 23],
       [ 4,  1, 91, 66],
       [ 1, 22,  9, 98],
       [97, 88, 45, 12],
       [38, 33,  2, 48],
       [65, 65, 46, 52]])

In [12]:
np.flip(b,axis=0)  # Flipping along the first axis (rows)   

array([[65, 65, 46, 52],
       [38, 33,  2, 48],
       [97, 88, 45, 12],
       [ 1, 22,  9, 98],
       [ 4,  1, 91, 66],
       [50,  7, 62, 23]])