In [1]:
import numpy as np
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[40, 70, 29, 91],
       [25, 74, 98,  1],
       [58, 82, 95, 25],
       [ 6, 86,  3, 70],
       [ 8, 47, 93, 19],
       [83, 23, 62, 75]])

In [4]:
a=np.random.randint(1,100,15)
a

array([53, 58, 11, 74, 58, 21, 53,  2, 86, 14,  7,  4, 93, 89, 88])

In [6]:
## np.put(a, indices, values) function helps to replace the elements of a with values at the specified indices.
np.put(a,[0,1],[53,58])

In [8]:
## np.delete(a, indices) function helps to delete the elements of a at the specified indices.
np.delete(a,[0,1])

array([11, 74, 58, 21, 53,  2, 86, 14,  7,  4, 93, 89, 88])