In [1]:
## all the set functions in numpy
import numpy as np
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])



In [2]:
np.union1d(m, n)  # Union of two arrays 


array([1, 2, 3, 4, 5, 6, 7])

In [3]:
np.intersect1d(m, n)  # Intersection of two arrays

array([3, 4, 5])

In [6]:
np.setdiff1d(n, m)  # Set difference of two arrays

array([6, 7])

In [7]:
np.setxor1d(m, n)  # Set symmetric difference of two arrays

array([1, 2, 6, 7])

In [8]:
np.in1d(m, n)  # Test whether each element of a 1-D array is also present in a second array

array([False, False,  True,  True,  True])