## np.append

#### numpy.concatenate()function concatenates a sequence of arrays along an existing axis.


In [2]:
import numpy as np
a=np.random.randint(1,100,15)

In [3]:
np.append(a,200)

array([ 10,  10,  36,  22,  17,  18,  83,  18,  53,   9,  36,  34,  98,
        72,  45, 200])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[87, 31, 41, 33],
       [19, 83, 33, 37],
       [86, 17, 35, 12],
       [32, 13, 41, 72],
       [ 1, 37, 76, 13],
       [91,  6, 45, 87]])

In [5]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[87., 31., 41., 33.,  1.],
       [19., 83., 33., 37.,  1.],
       [86., 17., 35., 12.,  1.],
       [32., 13., 41., 72.,  1.],
       [ 1., 37., 76., 13.,  1.],
       [91.,  6., 45., 87.,  1.]])