In [1]:
## expand_dims fullform is np.expand_dims
## we can convert 1d array to 2d array by using expand_dims
## code
import numpy as np
a=np.random.randint(1,100,15)
a


array([56, 64, 68, 28, 42, 34, 34, 87, 20, 48, 44, 32, 94, 27,  4])

In [2]:
np.expand_dims(a, axis=0)  # Convert to 2D array with one row

array([[56, 64, 68, 28, 42, 34, 34, 87, 20, 48, 44, 32, 94, 27,  4]])

In [3]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [4]:
np.expand_dims(a, axis=1)  # Convert to 2D array with one column

array([[56],
       [64],
       [68],
       [28],
       [42],
       [34],
       [34],
       [87],
       [20],
       [48],
       [44],
       [32],
       [94],
       [27],
       [ 4]])