In [1]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([52, 58,  4, 39, 86, 13, 36, 38, 52, 95, 19, 51, 57, 81, 88])

In [2]:
#find all the indices with value greater than 50
np.where(a > 50)

(array([ 0,  1,  4,  8,  9, 11, 12, 13, 14]),)

In [3]:
## replace all values greater than 50 with 0
np.where(a > 50, 0, a) # np.whre(condition, value_if_true, value_if_false)

array([ 0,  0,  4, 39,  0, 13, 36, 38,  0,  0, 19,  0,  0,  0,  0])

In [ ]:
##replace all the even values with 0
np.where(a % 2 == 0, 0, a) # np.where(condition, value_if_true, value_if_false)

array([ 0,  0,  0, 39,  0, 13,  0,  0,  0, 95, 19, 51, 57, 81,  0])