## np.argmax
#### The numpy function `np.argmax` returns the indices of the maximum values along an axis.

```python

In [1]:
import numpy as np  
a=np.random.randint(1,100,15)
a


array([76, 60,  4, 75, 85, 65, 50, 93, 70, 26, 78, 39, 37, 88, 63])

In [2]:
np.argmax(a)  # Returns the index of the maximum value in the array

7

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[63, 87, 91, 58],
       [10, 20, 60, 19],
       [ 8, 42, 69, 81],
       [59, 62, 26, 96],
       [58, 43, 92, 20],
       [37, 38, 74, 27]])

In [5]:
np.argmax(b, axis=0)  # Returns the indices of the maximum values along the first axis (columns)


array([0, 0, 4, 3])

In [6]:
np.argmax(b, axis=1)  # Returns the indices of the maximum values along the second axis (rows)

array([2, 2, 3, 3, 2, 2])

In [7]:
## np.argmin(a)  # Returns the index of the minimum value in the array  
np.argmin(a)


2