In [2]:
## np.cumsum is a function that returns the cumulative sum of the elements along a given axis.
import numpy as np
a=np.random.randint(1,100,15)
a


array([74, 52, 98, 32, 56, 21, 91, 67, 26, 18, 27, 53, 75, 81, 56])

In [3]:
np.cumsum(a)

array([ 74, 126, 224, 256, 312, 333, 424, 491, 517, 535, 562, 615, 690,
       771, 827])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[92, 95, 24, 31],
       [42, 50, 74, 20],
       [25, 90, 46, 31],
       [55, 75, 18, 99],
       [77, 22, 22,  7],
       [ 3, 45, 58, 59]])

In [5]:
np.cumsum(b, axis=0)  # Cumulative sum along the first axis (columns)

array([[ 92,  95,  24,  31],
       [134, 145,  98,  51],
       [159, 235, 144,  82],
       [214, 310, 162, 181],
       [291, 332, 184, 188],
       [294, 377, 242, 247]])

In [6]:
np.cumsum(b, axis=1)  # Cumulative sum along the second axis (rows)

array([[ 92, 187, 211, 242],
       [ 42,  92, 166, 186],
       [ 25, 115, 161, 192],
       [ 55, 130, 148, 247],
       [ 77,  99, 121, 128],
       [  3,  48, 106, 165]])

In [7]:
## np.cumprod is a function that returns the cumulative product of the elements along a given axis.
np.cumprod(a)

array([                  74,                 3848,               377104,
                   12067328,            675770368,          14191177728,
              1291397173248,       86523610607616,     2249613875798016,
          40493049764364288,  1093312343637835776,  2605321991676641280,
       -7515035435056971776,    24684192800489472,  1382314796827410432])